interfaceFontFamily: Microsoft YaHei UI
interfaceFontSize: 14
windowWidth: 1000
windowHeight: 600
windowLeft: 240
windowTop: 156
windowState: 0
leftPanelWidth: 260
masterPasswordAsked: false
masterPasswordSkipped: true
